from django.conf.urls import url
from django.views.generic import TemplateView
# from .views import DashboardPage

urlpatterns = [
    url('doc/', TemplateView.as_view(template_name="documentation.html")),
    url('dashboard/', TemplateView.as_view(template_name="index.html")),
    url('buttons/', TemplateView.as_view(template_name="buttons.html")),
    url('icons/', TemplateView.as_view(template_name="icons.html")),
    url('grid/', TemplateView.as_view(template_name="grid.html")),
    url('widgets/', TemplateView.as_view(template_name="widgets.html")),
    url('components/', TemplateView.as_view(template_name="components.html")),
    url('list/', TemplateView.as_view(template_name="list.html")),
    url('form-elements/', TemplateView.as_view(template_name="form-elements.html")),
    url('form-validation/', TemplateView.as_view(template_name="form-validation.html")),
    url('form-wizard/', TemplateView.as_view(template_name="form-wizard.html")),
    url('chart/', TemplateView.as_view(template_name="chart.html")),
    url('fullcalendar/', TemplateView.as_view(template_name="fullcalendar.html")),
    url('portlet/', TemplateView.as_view(template_name="portlet.html")),
    url('timeline/', TemplateView.as_view(template_name="timeline.html")),
    url('gallery/', TemplateView.as_view(template_name="gallery.html")),
    url('profile/', TemplateView.as_view(template_name="profile.html")),
    url('invoice/', TemplateView.as_view(template_name="invoice.html")),
    url('intro/', TemplateView.as_view(template_name="intro.html")),
    url('master/', TemplateView.as_view(template_name="master.html")),
    url('gmap/', TemplateView.as_view(template_name="gmap.html")),
    url('jvectormap/', TemplateView.as_view(template_name="jvectormap.html")),
    url('signin/', TemplateView.as_view(template_name="signin.html")),
    url('signup/', TemplateView.as_view(template_name="signup.html")),
    url('404/', TemplateView.as_view(template_name="404.html")),
    url('docs/', TemplateView.as_view(template_name="docs.html")),
    url('mail/', TemplateView.as_view(template_name="mail.html")),
    url('notebook/', TemplateView.as_view(template_name="notebook.html")),
    url('price/', TemplateView.as_view(template_name="price.html")),
    url('layout-c/', TemplateView.as_view(template_name="layout-c.html")),
    url('layout-r/', TemplateView.as_view(template_name="layout-r.html")),
    url('layout-h/', TemplateView.as_view(template_name="layout-h.html")),
    url('table-static/', TemplateView.as_view(template_name="table-static.html")),
    url('table-datatable/', TemplateView.as_view(template_name="table-datatable.html")),
    url('table-datagrid/', TemplateView.as_view(template_name="table-datagrid.html")),
    url('modal.lockme/', TemplateView.as_view(template_name="modal.lockme.html")),
    url('landing/', TemplateView.as_view(template_name="landing.html")),
    url('features/', TemplateView.as_view(template_name="features.html")),
    url('blog/', TemplateView.as_view(template_name="blog.html")),
    url('signup/', TemplateView.as_view(template_name="signup.html")),
    url('use_case/experience_share', TemplateView.as_view(template_name="ExperienceSharingUseCase.html")),
    url('use_case/all', TemplateView.as_view(template_name="use_cases.html")),
]
